name: 3d_bb_fix
channels:
  - nvidia/label/cuda-11.8.0
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - cuda-toolkit=11.8.0
  - gcc_linux-64=11.4.0
  - gxx_linux-64=11.4.0
  - libxcrypt
  - cmake
  - numpy=2.0.2
  - pip
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu118
      - torch==2.0.1+cu118
      - torchvision==0.15.2+cu118
      - ninja
      - pydantic
      - hydra-core
      - pytorch-lightning